inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.2
  DisplayCopNames: true
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-rails

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/Documentation:
  Enabled: false
